- name: Nagios path
  file:
    dest: /opt/nagios
    state: directory
    mode: 0755

- name: Download nagios
  get_url:
    url: http://assets.nagios.com/downloads/nagiosxi/xi-latest.tar.gz
    dest: /opt/nagios
    mode: 0755

- name: unarchive nagios
  unarchive:
    src: /opt/nagios/xi-latest.tar.gz
    dest: /opt/nagios
    remote_src: True

- name: run fullinstall
  shell: ./fullinstall -n chdir=/opt/nagios/nagiosxi creates=/etc/pki/rpm-gpg/RPM-GPG-KEY-NAGIOS
