- name: Create /opt/splunk
  file:
    dest: /opt/splunk
    state: directory
    mode: 0755

- name: download splunk
  get_url:
    url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=6.5.2&product=universalforwarder&filename=splunkforwarder-6.5.2-67571ef4b87d-Linux-x86_64.tgz&wget=true
    dest: /opt/splunk

- name: unzip
  unarchive:
       src: /opt/splunk/splunkforwarder-6.5.2-67571ef4b87d-Linux-x86_64.tgz
       dest: /opt/splunk/
       remote_src: True


- name: start splunk Forwarder
  command: chdir=/opt/splunk/splunkforwarder/bin ./splunk start --accept-license
